ANDROID: Fix for kernelci !CONFIG_SMP break-breaks
ab9c52146ff6 ("ANDROID: cgroup: Add vendor hook for rebuild_root_domains_bypass")
introduced a hook that declared a parameter whose name collided with a
global variable. If !CONFIG_SMP, this global variable is instead a
compile-time constant which causes this error:

include/linux/cpu.h:101:28: error: expected ‘;’, ‘,’ or ‘)’ before numeric constant

Fixes: ab9c52146ff6 ("ANDROID: cgroup: Add vendor hook for rebuild_root_domains_bypass")
Signed-off-by: Todd Kjos <tkjos@google.com>
Change-Id: I7831c5067be2ee548e8f6885eec99ab9085414fa