ANDROID: teo: Extend ifdef protection for accessing sched_cpu_util
sched_cpu_util() is conditional on CONFIG_CPU_FREQ_GOV_SCHEDUTIL=y
beside CONFIG_SMP=y.

In 5.15 and 6.1 LTS schedutil_cpu_util() has moved to core.c, and then
sched_cpu_util() was added there. Since we had to manually pull in
sched_cpu_util() and define it in cpufreq_schedutil.c where
schedutil_cpu_util() currently lives; we do have the additional deps on
schedutil being enabled in the config to use teo util.

Fixes build error caught by lkp test robot.

	>> teo.c:(.text+0x6c8): undefined reference to `sched_cpu_util'

Bug: 258723112
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Qais Yousef <qyousef@google.com>
Change-Id: Ica85a887d3e004af64ea2d9b46d6160ebdfac651
(cherry picked from commit 067da03e3376434225212747523f7c5f85ad06a2)
Signed-off-by: Panchajanya1999 <kernel@panchajanya.dev>